(() => {
  let postFollowups = [];

  const isDateInput = v => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(String(v || '').trim()) || /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/.test(String(v || '').trim());
  const hnTimestamp = v => String(v).trim().replace(' ', 'T') + ':00-06:00';
  const fmtFollowup = v => v ? new Date(v).toLocaleString('es-HN',{hour12:false}) : '';
  const dateTimeValue=(dateId,timeId)=>{const d=document.getElementById(dateId)?.value,t=document.getElementById(timeId)?.value;return d&&t?`${d}T${t}`:'';};
  const nowHN=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Tegucigalpa',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`};};
  window.setNowClinical=function(dateId,timeId){const n=nowHN(),d=document.getElementById(dateId),t=document.getElementById(timeId);if(d)d.value=n.date;if(t)t.value=n.time;};
  const dateTimeFields=(prefix,label,withNow=false)=>`<div class="actions" style="align-items:end;gap:8px;flex-wrap:wrap;margin-top:8px"><label style="margin:0">Fecha ${esc(label)}<input id="${prefix}-date" type="date" aria-label="Fecha ${esc(label)}"></label><label style="margin:0">Hora ${esc(label)} (24 h)<input id="${prefix}-time" type="time" step="60" aria-label="Hora ${esc(label)} en formato 24 horas"></label>${withNow?`<button type="button" class="ghost" onclick="setNowClinical('${prefix}-date','${prefix}-time')">Usar fecha y hora actual</button>`:''}</div>`;

  async function loadPostFollowups(){try{const {data,error}=await sb.from('seguimientos_postreferencia').select('*').order('creado_en',{ascending:false});if(error)throw error;postFollowups=data||[];}catch{postFollowups=[];}}
  function followupForTramo(id){return postFollowups.filter(x=>x.tramo_id===id).sort((a,b)=>(a.numero_control||0)-(b.numero_control||0));}
  function canCompletePuerperal(t){const c=caseOf(t.caso_id);if(!profile?.establecimiento_id||!c)return false;if(t.estado_actual==='HOSPITALIZADO')return profile.rol==='USUARIO_HOSPITAL'&&profile.establecimiento_id===t.establecimiento_destino_id;return profile.establecimiento_id===c.establecimiento_origen_inicial_id;}

  function deliveryRegistrationHtml(t){const c=caseOf(t.caso_id);if(!c||c.motivo!=='ATENCION_MATERNA')return '';const hospitalUser=profile?.rol==='USUARIO_HOSPITAL'&&profile?.establecimiento_id===t.establecimiento_destino_id;if(!hospitalUser)return '';const control1=followupForTramo(t.id).find(x=>x.tipo==='PUERPERAL'&&Number(x.numero_control||1)===1);const parto=control1?.fecha_base;const prefix=`parto-${t.id}`;return `<div class="notice ${parto?'ok':''}"><strong>Fecha y hora del parto</strong><br>${parto?`Registrada: <strong>${esc(fmtFollowup(parto))}</strong><br>`:'Debe registrarse para iniciar automáticamente los controles puerperales.<br>'}${dateTimeFields(prefix,'del parto',true)}<div class="actions"><button class="ghost" onclick="registerDelivery('${t.id}')">${parto?'Actualizar fecha/hora':'Registrar parto'}</button></div><small>Puede registrarlo un usuario hospitalario autorizado, incluida auxiliar de enfermería con perfil hospitalario.</small></div>`;}

  function followupHtml(t){const rows=followupForTramo(t.id);if(!rows.length)return '';return rows.map(s=>{if(s.tipo==='PUERPERAL'){const done=s.estado==='COMPLETADA',n=Number(s.numero_control||1);const action=!done&&canCompletePuerperal(t)?`<div class="actions"><button class="ghost" onclick="completePuerperal('${t.id}',${n})">Registrar control ${n} realizado</button></div>`:'';let schedule=n===1?`Primer control: entre <strong>${esc(fmtFollowup(s.ventana_desde))}</strong> y <strong>${esc(fmtFollowup(s.ventana_hasta))}</strong> (48–72 horas después del parto).`:n===2?`Segundo control: entre <strong>${esc(fmtFollowup(s.ventana_desde))}</strong> y <strong>${esc(fmtFollowup(s.ventana_hasta))}</strong> (3–7 días después del parto).`:n===3?`Tercer control: <strong>${esc(fmtFollowup(s.ventana_desde))}</strong> (40 días después del parto).`:`Control puerperal ${n}.`;const responsible=t.estado_actual==='HOSPITALIZADO'?'Responsable actual: hospital (paciente continúa ingresada).':'Responsable actual: establecimiento de origen después del alta.';return `<div class="notice ${done?'ok':''}"><strong>Control puerperal ${n}</strong><br>${done?`Control registrado como realizado${s.completado_en?` el <strong>${esc(fmtFollowup(s.completado_en))}</strong>`:''}.`:`${schedule}<br>${responsible}`} ${action}</div>`;}if(s.tipo==='CONSULTA_EXTERNA'){const pending=s.estado==='PENDIENTE_ASIGNACION',ageHours=(Date.now()-new Date(s.creado_en).getTime())/3600000,alertText=pending?(ageHours>=48?' · ALERTA ROJA: más de 48 h sin cita':ageHours>=24?' · ALERTA AMARILLA: más de 24 h sin cita':''):'';const action=pending&&profile?.establecimiento_id===t.establecimiento_destino_id?`<div class="actions"><button class="ghost" onclick="assignCeAppointment('${t.id}')">Asignar cita</button></div>`:'';return `<div class="notice"><strong>Consulta Externa</strong><br>${pending?`Cita pendiente de asignación${esc(alertText)}.`:`Cita programada para <strong>${esc(fmtFollowup(s.fecha_cita))}</strong>.`} ${action}</div>`;}return '';}).join('');}

  const baseTramoItem=tramoItem;tramoItem=function(t,withActions=true){const html=baseTramoItem(t,withActions),extra=deliveryRegistrationHtml(t)+followupHtml(t);if(!extra)return html;const i=html.lastIndexOf('</div>');return i>=0?html.slice(0,i)+extra+html.slice(i):html+extra;};
  const baseRefreshAll=refreshAll;refreshAll=async function(){await loadPostFollowups();await baseRefreshAll();};

  window.registerDelivery=async function(id){const value=dateTimeValue(`parto-${id}-date`,`parto-${id}-time`);if(!isDateInput(value))return alert('Seleccione la fecha y la hora del parto.');if(new Date(hnTimestamp(value)).getTime()>Date.now()+60000)return alert('La fecha y hora del parto no pueden estar en el futuro.');const existing=followupForTramo(id).find(x=>x.tipo==='PUERPERAL'&&Number(x.numero_control||1)===1)?.fecha_base;if(existing&&!confirm('Ya existe una fecha y hora de parto. ¿Desea actualizarla? El cambio quedará auditado y recalculará los controles puerperales.'))return;const {error}=await sb.rpc('sirro_registrar_parto',{p_tramo:id,p_fecha_parto:hnTimestamp(value)});if(error)return alert(error.message);await refreshAll();alert('Fecha y hora del parto registradas. Los tres controles puerperales fueron calculados automáticamente.');};

  answerTramo=async function(id){const detail=prompt('Escriba la respuesta / contrarreferencia:');if(!detail?.trim())return;const t=tramos.find(x=>x.id===id),c=caseOf(t?.caso_id);if(!t||!c)return;let citaEstado=null,fechaCita=null;if(String(c.motivo||'').startsWith('CE_')){const pending=confirm('CONSULTA EXTERNA\n\n¿La cita todavía está pendiente de asignación?\nAceptar = pendiente · Cancelar = registrar fecha y hora');if(pending)citaEstado='PENDIENTE_ASIGNACION';else{window.pendingCeAnswer={id,detail:detail.trim(),t,c};return openCeDateTime(id);}}const mode=t.parent_tramo_id&&confirm('¿Enviar la respuesta directamente al establecimiento que originó el caso?\nAceptar: respuesta directa.\nCancelar: respuesta por la cadena de referencia.')?'DIRECTO_ORIGINADOR':'ORIGEN_TRAMO';const {error}=await sb.rpc('sirro_enviar_respuesta_v3',{p_tramo:id,p_detalle:detail.trim(),p_modo:mode,p_parto:null,p_fecha_alta:null,p_cita_estado:citaEstado,p_fecha_cita:fechaCita});if(error)return alert(error.message);await refreshAll();};

  window.openCeDateTime=function(id){const t=tramos.find(x=>x.id===id);if(!t)return;const box=document.createElement('div');box.id='sirroDateTimeModal';box.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px';box.innerHTML=`<div class="card" style="max-width:520px;width:100%"><h3>Fecha y hora de cita</h3>${dateTimeFields(`ce-${id}`,'de la cita')}<div class="actions"><button class="primary" onclick="saveCeDateTime('${id}')">Guardar cita</button><button class="ghost" onclick="closeClinicalDateTime()">Cancelar</button></div></div>`;document.body.appendChild(box);};
  window.closeClinicalDateTime=()=>document.getElementById('sirroDateTimeModal')?.remove();
  window.saveCeDateTime=async function(id){const value=dateTimeValue(`ce-${id}-date`,`ce-${id}-time`);if(!isDateInput(value))return alert('Seleccione fecha y hora de la cita.');const pending=window.pendingCeAnswer;if(pending?.id===id){const t=pending.t,mode=t.parent_tramo_id&&confirm('¿Enviar la respuesta directamente al establecimiento que originó el caso?\nAceptar: respuesta directa.\nCancelar: respuesta por la cadena de referencia.')?'DIRECTO_ORIGINADOR':'ORIGEN_TRAMO';const {error}=await sb.rpc('sirro_enviar_respuesta_v3',{p_tramo:id,p_detalle:pending.detail,p_modo:mode,p_parto:null,p_fecha_alta:null,p_cita_estado:'PROGRAMADA',p_fecha_cita:hnTimestamp(value)});if(error)return alert(error.message);window.pendingCeAnswer=null;}else{const {error}=await sb.rpc('sirro_asignar_cita_ce',{p_tramo:id,p_fecha_cita:hnTimestamp(value)});if(error)return alert(error.message);}closeClinicalDateTime();await refreshAll();};
  window.assignCeAppointment=async function(id){window.pendingCeAnswer=null;openCeDateTime(id);};

  window.completePuerperal=async function(id,numeroControl){const prefix=`control-${id}-${numeroControl}`,box=document.createElement('div');box.id='sirroDateTimeModal';box.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px';box.innerHTML=`<div class="card" style="max-width:540px;width:100%"><h3>Control puerperal ${numeroControl}</h3>${dateTimeFields(prefix,'del control',true)}<label>Observación (opcional)<textarea id="${prefix}-obs" rows="3"></textarea></label><div class="actions"><button class="primary" onclick="savePuerperalControl('${id}',${numeroControl},'${prefix}')">Registrar control</button><button class="ghost" onclick="closeClinicalDateTime()">Cancelar</button></div></div>`;document.body.appendChild(box);setNowClinical(`${prefix}-date`,`${prefix}-time`);};
  window.savePuerperalControl=async function(id,numeroControl,prefix){const value=dateTimeValue(`${prefix}-date`,`${prefix}-time`);if(!isDateInput(value))return alert('Seleccione la fecha y hora real del control.');if(new Date(hnTimestamp(value)).getTime()>Date.now()+60000)return alert('La fecha y hora del control no pueden estar en el futuro.');const obs=document.getElementById(`${prefix}-obs`)?.value.trim()||null;const {error}=await sb.rpc('sirro_completar_control_puerperal_v2',{p_tramo:id,p_numero_control:numeroControl,p_fecha_control:hnTimestamp(value),p_observacion:obs});if(error)return alert(error.message);closeClinicalDateTime();await refreshAll();};

  const start=async()=>{await loadPostFollowups();try{renderTracking();renderReceived();}catch{}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
