(() => {
  let pendientesFollowups=[]; let activeRows=[]; let started=false;
  const now=()=>Date.now(),getProfile=()=>typeof profile!=='undefined'?profile:null,getTramos=()=>typeof tramos!=='undefined'&&Array.isArray(tramos)?tramos:[],getNotifications=()=>typeof notifications!=='undefined'&&Array.isArray(notifications)?notifications:[],byCase=id=>typeof caseOf==='function'?(caseOf(id)||{}):{},tramoById=id=>getTramos().find(x=>x.id===id),safeFmt=v=>v&&typeof fmt==='function'?fmt(v):'',esc2=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
  const isClosedTramo=t=>!!t&&['CERRADO','CIERRE_ADMINISTRATIVO_EXTERNO'].includes(t.estado_actual);
  const isAuxiliar=()=>{const p=getProfile(),job=norm(p?.cargo_funcion);return p?.rol==='USUARIO_HOSPITAL'&&(p?.tipo_usuario_hospital==='AUXILIAR_ENFERMERIA'||job==='AE'||(job.includes('AUXILIAR')&&job.includes('ENFERMER')));};
  const isLicenciadaEnfermeria=()=>{const p=getProfile(),job=norm(p?.cargo_funcion);return p?.rol==='USUARIO_HOSPITAL'&&(p?.tipo_usuario_hospital==='LICENCIADA_ENFERMERIA'||(job.includes('LICENCIAD')&&job.includes('ENFERMER')));};
  const isHospitalSpecialist=()=>getProfile()?.rol==='USUARIO_HOSPITAL'&&getProfile()?.tipo_usuario_hospital==='MEDICO_ESPECIALISTA';
  const specialtyVisible=t=>!isHospitalSpecialist()||!window.SIRRO_SPECIALTY_FILTER?.belongsToCurrentSpecialist||window.SIRRO_SPECIALTY_FILTER.belongsToCurrentSpecialist(t);
  const caseVisible=id=>!isHospitalSpecialist()||getTramos().some(t=>String(t.caso_id)===String(id)&&specialtyVisible(t));
  const isObstetra=()=>{const p=getProfile(),specialty=norm(p?.especialidad),job=norm(p?.cargo_funcion);return p?.rol==='USUARIO_HOSPITAL'&&p?.tipo_usuario_hospital==='MEDICO_ESPECIALISTA'&&((specialty.includes('GINECO')&&specialty.includes('OBSTET'))||job.includes('OBSTETRA')||(job.includes('GINECO')&&job.includes('OBSTET')));};
  const canRegisterDelivery=()=>isAuxiliar()||isLicenciadaEnfermeria()||isObstetra();
  const canManagePuerperal=()=>isLicenciadaEnfermeria()||isObstetra();
  const hasDelivery=t=>pendientesFollowups.some(s=>String(s.tramo_id)===String(t?.id)&&s.tipo==='PUERPERAL'&&Number(s.numero_control||1)===1&&s.fecha_base);
  const needsDeliveryBeforeAnswer=t=>{const c=byCase(t?.caso_id);return !!t&&t.estado_actual==='HOSPITALIZADO'&&c?.motivo==='ATENCION_MATERNA'&&!hasDelivery(t);};
  function showTab(name){const b=document.querySelector(`#tabs button[data-tab="${name}"]`);if(!b)return;document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tabpane').forEach(x=>x.classList.add('hidden'));document.getElementById(`tab-${name}`)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}
  async function loadFollowups(){try{if(typeof fetchAll!=='function')return;pendientesFollowups=await fetchAll('seguimientos_postreferencia');if(!Array.isArray(pendientesFollowups))pendientesFollowups=[];}catch{pendientesFollowups=[];}}
  function responsablePuerperal(t,c){const p=getProfile();if(!p?.establecimiento_id)return false;if(t.estado_actual==='HOSPITALIZADO')return canManagePuerperal()&&p.establecimiento_id===t.establecimiento_destino_id;return p.establecimiento_id===c.establecimiento_origen_inicial_id;}
  function priorityForWindow(s){if(!s?.ventana_desde)return {rank:3,label:'PENDIENTE'};const n=now(),desde=new Date(s.ventana_desde).getTime(),hasta=s.ventana_hasta?new Date(s.ventana_hasta).getTime():desde;if(n>hasta)return {rank:0,label:'VENCIDO'};if(n>=desde)return {rank:1,label:'REQUIERE ATENCIÓN'};if(desde-n<=24*3600000)return {rank:2,label:'PRÓXIMO'};return {rank:3,label:'PENDIENTE'};}
  function buildActions(){const out=[],p=getProfile();if(!p)return out;const aux=isAuxiliar();const pushAction=(t,row)=>out.push({...row,tramoId:t?.id||null,casoId:t?.caso_id||null});for(const t of getTramos()){if(!specialtyVisible(t))continue;const c=byCase(t.caso_id),detail=`${c.codigo_visible||''} · ${c.paciente_nombre||''}`;
      if(isHospitalSpecialist()&&c.motivo==='ATENCION_MATERNA'&&!isObstetra())continue;
      if(aux){if(p.establecimiento_id===t.establecimiento_destino_id&&t.estado_actual==='HOSPITALIZADO'&&c.motivo==='ATENCION_MATERNA'&&!hasDelivery(t))pushAction(t,{rank:1,type:'accion',title:'Registrar fecha y hora del parto',detail,button:'Registrar parto',run:()=>showTab('recibidas')});continue;}
      if(p.establecimiento_id===t.establecimiento_destino_id){if(t.estado_actual==='ENVIADO')pushAction(t,{rank:1,type:'accion',title:'Referencia por recibir',detail,button:'Abrir recibidas',run:()=>showTab('recibidas')});if(t.estado_actual==='EN_ATENCION')pushAction(t,{rank:2,type:'accion',title:'Evaluación pendiente',detail,button:'Registrar evaluación',run:()=>typeof evaluateTramo==='function'&&evaluateTramo(t.id)});if(canRegisterDelivery()&&t.estado_actual==='HOSPITALIZADO'&&c.motivo==='ATENCION_MATERNA'&&!hasDelivery(t))pushAction(t,{rank:1,type:'accion',title:'Registrar fecha y hora del parto',detail,button:'Registrar parto',run:()=>showTab('recibidas')});else if(['EVALUADO','HOSPITALIZADO'].includes(t.estado_actual))pushAction(t,{rank:1,type:'accion',title:'Respuesta / contrarreferencia pendiente',detail,button:'Responder',run:()=>typeof answerTramo==='function'&&answerTramo(t.id)});}
      if(p.establecimiento_id===t.establecimiento_origen_id){if(t.estado_actual==='RESPUESTA_ENVIADA')pushAction(t,{rank:1,type:'accion',title:'Respuesta lista para confirmar',detail,button:'Revisar y cerrar',run:()=>typeof closeTramo==='function'&&closeTramo(t.id)});if(t.estado_actual==='RECHAZADO')pushAction(t,{rank:0,type:'accion',title:'Referencia rechazada por corregir',detail,button:'Corregir y reenviar',run:()=>typeof reorientTramo==='function'&&reorientTramo(t.id)});}}
    if(!aux)for(const s of pendientesFollowups){if(s.estado==='COMPLETADA')continue;const t=tramoById(s.tramo_id);if(!t||!specialtyVisible(t))continue;const c=byCase(t.caso_id);if(isHospitalSpecialist()&&c.motivo==='ATENCION_MATERNA'&&!isObstetra())continue;const detail=`${c.codigo_visible||''} · ${c.paciente_nombre||''}${s.ventana_desde?` · ${safeFmt(s.ventana_desde)}`:''}`;if(s.tipo==='PUERPERAL'&&responsablePuerperal(t,c)){const n=Number(s.numero_control||1),pri=priorityForWindow(s),desde=s.ventana_desde?new Date(s.ventana_desde).getTime():0,open=!!desde&&now()>=desde;pushAction(t,{rank:pri.rank,type:open?'accion':'proximo',title:`Control puerperal ${n} · ${open?pri.label:'PRÓXIMO'}`,detail,button:open?'Registrar control':null,availableText:!open&&s.ventana_desde?`Disponible desde ${safeFmt(s.ventana_desde)}`:null,run:open?()=>window.completePuerperal?.(t.id,n):null});}if(s.tipo==='CONSULTA_EXTERNA'&&s.estado==='PENDIENTE_ASIGNACION'&&!isClosedTramo(t)&&p.establecimiento_id===t.establecimiento_destino_id){const age=(now()-new Date(s.creado_en).getTime())/3600000;pushAction(t,{rank:age>=48?0:age>=24?1:2,type:'accion',title:'Cita de consulta externa pendiente',detail,button:'Asignar cita',run:()=>window.assignCeAppointment?.(t.id)});}}
    if(!aux){const actionTramos=new Set(out.filter(x=>x.type==='accion'&&x.tramoId).map(x=>String(x.tramoId))),actionCases=new Set(out.filter(x=>x.type==='accion'&&x.casoId).map(x=>String(x.casoId)));for(const n of getNotifications().filter(n=>!n.leida)){const nt=n.tramo_id!=null?String(n.tramo_id):null,nc=n.caso_id!=null?String(n.caso_id):null;const notificationTramo=nt?getTramos().find(t=>String(t.id)===nt):null;if(notificationTramo&&isClosedTramo(notificationTramo))continue;if(notificationTramo&&!specialtyVisible(notificationTramo))continue;if(!notificationTramo&&nc&&!caseVisible(nc))continue;if((nt&&actionTramos.has(nt))||(nc&&actionCases.has(nc)))continue;out.push({rank:n.critica?1:3,type:'info',title:n.titulo||'Aviso',detail:n.mensaje||'',fecha:n.creada_en,button:'Abrir notificaciones',run:()=>showTab('notificaciones')});}}return out.sort((a,b)=>a.rank-b.rank);}
  const group=x=>x.rank===0?'pending':x.rank===1?'attention':'upcoming',colors={pending:{bg:'#fff1f2',border:'#dc2626',text:'#991b1b'},attention:{bg:'#fffbeb',border:'#d97706',text:'#92400e'},upcoming:{bg:'#f8fafc',border:'#94a3b8',text:'#475569'}};
  function ensureUI(){if(document.getElementById('sirroPendingCard'))return true;const inicio=document.getElementById('tab-inicio');if(!inicio)return false;const card=document.createElement('article');card.id='sirroPendingCard';card.className='card';card.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">LO QUE TENGO PENDIENTE</h2><p class="muted" style="margin:6px 0 0">Rojo = pendiente/vencido · Amarillo = requiere mi atención.</p></div><button type="button" onclick="window.openSirroPending('all')">LO PENDIENTE · <span id="sirroPendingCount">0</span></button></div><div id="sirroPendingPreview" style="margin-top:10px"></div><div id="sirroPendingDetails" style="margin-top:12px"></div>`;const flow=[...inicio.querySelectorAll(':scope > article.card')].find(x=>x.querySelector('h2')?.textContent?.includes('Flujo SIRRO'));if(flow)inicio.insertBefore(card,flow);else inicio.appendChild(card);return true;}
  function homeButton(kind,count,label){const c=colors[kind];return `<button type="button" onclick="window.openSirroPending('${kind}')" style="background:${c.bg};border:2px solid ${c.border};color:${c.text};padding:12px 16px;border-radius:12px;font:inherit;font-weight:750;cursor:pointer">${count} ${label}</button>`;}
  function renderHome(){if(!ensureUI())return;const rows=buildActions(),box=document.getElementById('sirroPendingPreview'),count=document.getElementById('sirroPendingCount');if(!box)return;if(count)count.textContent=rows.length;const details=document.getElementById('sirroPendingDetails');if(!rows.length){box.innerHTML='<div class="notice ok"><strong>Sin pendientes.</strong> No tiene acciones pendientes en este momento.</div>';if(details)details.innerHTML='';return;}const red=rows.filter(x=>group(x)==='pending').length,yellow=rows.filter(x=>group(x)==='attention').length,other=rows.length-red-yellow;box.innerHTML=`<div style="display:flex;gap:8px;flex-wrap:wrap">${homeButton('pending',red,red===1?'PENDIENTE':'PENDIENTES')}${homeButton('attention',yellow,yellow===1?'REQUIERE MI ATENCIÓN':'REQUIEREN MI ATENCIÓN')}${other?homeButton('upcoming',other,other===1?'PRÓXIMO / AVISO':'PRÓXIMOS / AVISOS'):''}</div>`;if(details&&activeRows.length){activeRows=activeRows.filter(x=>buildActions().some(y=>String(y.tramoId||'')===String(x.tramoId||'')&&y.title===x.title));if(!activeRows.length)details.innerHTML='';}}
  function rowHtml(x,i){const c=colors[group(x)],action=x.button&&typeof x.run==='function'?`<div class="actions"><button type="button" onclick="window.runSirroPendingAction(${i})">${esc2(x.button)}</button></div>`:x.availableText?`<div class="actions"><span class="badge" style="background:${c.bg};color:${c.text};border:1px solid ${c.border}">${esc2(x.availableText)}</span></div>`:'';return `<div style="padding:12px;margin:9px 0;border-radius:10px;background:${c.bg};border:2px solid ${c.border};color:${c.text}"><strong>${esc2(x.title)}</strong><br><small>${esc2(x.detail||'')}</small>${x.fecha?`<br><small>${esc2(safeFmt(x.fecha))}</small>`:''}${action}</div>`;}
  window.openSirroPending=function(kind='all'){const all=buildActions();activeRows=kind==='all'?all:all.filter(x=>group(x)===kind);const box=document.getElementById('sirroPendingDetails');if(!box)return;const title=kind==='pending'?'PENDIENTES / VENCIDOS':kind==='attention'?'REQUIERE MI ATENCIÓN':kind==='upcoming'?'PRÓXIMOS / INFORMATIVOS':'LO PENDIENTE';box.innerHTML=`<div class="notice"><strong>${title}</strong></div>${activeRows.length?activeRows.map(rowHtml).join(''):'<div class="notice ok">No hay elementos en esta categoría.</div>'}`;box.scrollIntoView({behavior:'smooth',block:'nearest'});};
  window.runSirroPendingAction=async function(i){const x=activeRows[Number(i)];if(!x||typeof x.run!=='function')return;await x.run();if(typeof window.refreshAll==='function')await window.refreshAll();else{await loadFollowups();renderHome();}const details=document.getElementById('sirroPendingDetails');if(details)details.innerHTML='';activeRows=[];};
  function installObstetricAnswerGuard(){const original=window.answerTramo;if(typeof original!=='function'||original.__sirroDeliveryRequired)return;const wrapped=async function(id){const t=getTramos().find(x=>String(x.id)===String(id));const c=byCase(t?.caso_id);if(isHospitalSpecialist()&&c?.motivo==='ATENCION_MATERNA'&&!isObstetra())return alert('Esta referencia obstétrica corresponde al perfil de Gineco-Obstetricia.');if(needsDeliveryBeforeAnswer(t)){alert('Antes de enviar la respuesta o contrarreferencia debe registrarse la fecha y la hora del parto.');showTab('recibidas');return;}return original.apply(this,arguments);};wrapped.__sirroDeliveryRequired=true;window.answerTramo=wrapped;}
  const baseRefresh=typeof window.refreshAll==='function'?window.refreshAll:null;if(baseRefresh)window.refreshAll=async function(){await baseRefresh();await loadFollowups();installObstetricAnswerGuard();renderHome();};
  function loadClosedPuerperalContinuity(){if(document.querySelector('script[src="./closed-puerperal-continuity.js"]'))return;const s=document.createElement('script');s.src='./closed-puerperal-continuity.js';document.body.appendChild(s);}
  async function start(){if(started)return;started=true;ensureUI();await loadFollowups();installObstetricAnswerGuard();renderHome();if(!document.querySelector('script[src="./puerperal-window-guard.js"]')){const s=document.createElement('script');s.src='./puerperal-window-guard.js';s.onload=loadClosedPuerperalContinuity;document.body.appendChild(s);}else loadClosedPuerperalContinuity();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('pageshow',()=>{ensureUI();installObstetricAnswerGuard();renderHome();});window.addEventListener('sirro-specialty-filtered',renderHome);
})();