const CACHE='sirro-v029';
const ASSETS=['./','./index.html','./config.js','./manifest.webmanifest','./icon-192.png','./icon-512.png','./logo-region-olancho.png','./viza-logo.svg','./followup.js'];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener('activate',e=>e.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))))])));
const injectFeatures=html=>{
  let out=html;
  if(!out.includes('id="vizaBrandLink"'))out=out.replace('</body>',`<style>#installHelp{display:flex;align-items:center;justify-content:center;gap:6px;flex-wrap:wrap}#vizaBrandLink{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;line-height:0;flex:0 0 auto}#vizaBrand{width:42px;height:42px;object-fit:contain;opacity:.55;filter:drop-shadow(0 1px 2px #0002);transition:opacity .2s ease,transform .2s ease}#vizaBrandLink:hover #vizaBrand,#vizaBrandLink:focus #vizaBrand{opacity:.8;transform:scale(1.04)}@media(max-width:760px){#vizaBrand{width:36px;height:36px}}</style><script>(()=>{const X_PROFILE='https://x.com/victorzepedaa';const ensure=()=>{const l=document.getElementById('loginView'),h=document.getElementById('installHelp');if(!h)return;let a=document.getElementById('vizaBrandLink');if(!a){a=document.createElement('a');a.id='vizaBrandLink';a.href=X_PROFILE;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label','Abrir perfil de ViZA en X');const img=document.createElement('img');img.id='vizaBrand';img.src='viza-logo.svg';img.alt='ViZA';a.appendChild(img);h.appendChild(a)}a.style.display=l&&!l.classList.contains('hidden')?'inline-flex':'none'};const start=()=>{ensure();const l=document.getElementById('loginView');const h=document.getElementById('installHelp');if(l)new MutationObserver(ensure).observe(l,{attributes:true,attributeFilter:['class']});if(h)new MutationObserver(()=>setTimeout(ensure,0)).observe(h,{childList:true,characterData:true,subtree:true})};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start()})();</script></body>`);
  return out;
};
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(e.request.mode==='navigate'||u.pathname.endsWith('/index.html')||u.pathname==='/'){e.respondWith(fetch(e.request,{cache:'no-store'}).then(async r=>{const h=injectFeatures(await r.text());const out=new Response(h,{status:r.status,statusText:r.statusText,headers:r.headers});caches.open(CACHE).then(c=>c.put(e.request,out.clone()));return out}).catch(()=>caches.match('./index.html').then(async r=>r?new Response(injectFeatures(await r.text()),{headers:r.headers}):r)));return}e.respondWith(fetch(e.request).then(r=>{const clone=r.clone();caches.open(CACHE).then(c=>c.put(e.request,clone));return r}).catch(()=>caches.match(e.request)))});